name = "QMDP"
uuid = "3aa3ecc9-5a5d-57c8-8188-3e47bd8068d2"
repo = "https://github.com/JuliaPOMDP/QMDP.jl"
version = "0.1.5"

[deps]
DiscreteValueIteration = "4b033969-44f6-5439-a48b-c11fa3648068"
POMDPLinter = "f3bd98c0-eb40-45e2-9eb1-f2763262d755"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPPolicies = "182e52fb-cfd0-5e46-8c26-fd0667c990f4"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
julia = "1"
POMDPModelTools = "0.1, 0.2, 0.3"
POMDPPolicies = "0.1.4, 0.2, 0.3, 0.4"
POMDPLinter = "0.1"
DiscreteValueIteration = "0.4"
POMDPs = "0.9.0"
BeliefUpdaters = "0.2"
POMDPModels = "0.4"
POMDPTesting = "0.2"

[extras]
BeliefUpdaters = "8bb6e9a1-7d73-552c-a44a-e5dc5634aac4"
POMDPModels = "355abbd5-f08e-5560-ac9e-8b5f2592a0ca"
POMDPTesting = "92e6a534-49c2-5324-9027-86e3c861ab81"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["BeliefUpdaters", "POMDPModels", "POMDPTesting", "Test"]
